create table if not exists public.ghl_integrations (
  id bigint generated by default as identity primary key,
  location_id text not null,
  private_integration_token text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists ghl_integrations_location_idx on public.ghl_integrations (location_id);
create index if not exists ghl_integrations_active_idx on public.ghl_integrations (active);

alter table public.ghl_integrations enable row level security;
revoke all on table public.ghl_integrations from anon, authenticated;
